server:
  port: 8071

spring:
  application:
    name: config-server
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: git@github.com:learnGrowD/best-prc-config.git
          ignore-local-ssh-settings: true
          host-key: AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=
          host-key-algorithm: ecdsa-sha2-nistp256
          private-key: |
                        -----BEGIN EC PRIVATE KEY-----
                        MHcCAQEEIC/Yq3UZm/VqhQv4plwt/gcASOAVKwv1kc5+/OMhP84MoAoGCCqGSM49
                        AwEHoUQDQgAEHoma4TcKxVxZu0QHh2e3dpckNfSjxH9VnYKvxI9qfePEQM3HhtII
                        vVb/ZXKhvITsJ36Fcv9fZV53jRA7a0VPLw==
                        -----END EC PRIVATE KEY-----

management:
  endpoints:
    web:
      exposure:
        include: "*"